// Copyright 2021 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char             3
#define gattdb_database_hash                    6
#define gattdb_client_support_features          8
#define gattdb_device_name                     11
#define gattdb_ota_control                     23
#define gattdb_ln_feature                      26
#define gattdb_location_and_speed              28
#define gattdb_position_quality                31
#define gattdb_ln_control_point                33
#define gattdb_navigation                      36
#define gattdb_descriptor_value_changed         40
#define gattdb_pressure                        43
#define gattdb_es_measurement_11               45
#define gattdb_es_trigger_setting_11           46
#define gattdb_es_configuration_11             47
#define gattdb_characteristic_user_description_11         48
#define gattdb_valid_range_11                  49
#define gattdb_temperature_measurement         52
#define gattdb_temperature_type                55
#define gattdb_intermediate_temperature         57
#define gattdb_measurement_interval            60
#define gattdb_valid_range_21                  62
#define gattdb_digital_out                     65
#define gattdb_characteristic_presentation_format         67
#define gattdb_characteristic_user_description         68
#define gattdb_characteristic_extended_properties         69
#define gattdb_value_trigger_setting           70
#define gattdb_time_trigger_setting            71
#define gattdb_number_of_digitals              72
#define gattdb_tx_power_level                  75

#endif
